---
# handlers file for quagga

- name: start quagga
  systemd:
    name: '{{ item }}'
    enabled: yes
    masked: no
    state: restarted
  with_items:
    - 'zebra.service'
    - 'ospfd.service'
...