---

- hosts: all
  become: yes
  tasks:
    - name: Install EPEL
      yum:
        name:
           - epel-release
        state: latest
    
    - name: Install PKG
      yum:
        name:
          - iperf3
          - tcpdump
          - nano
          - traceroute
          - openvpn
          - easy-rsa
        state: latest          

- hosts: server
  become: yes
  tasks:
    - name: generate static key
      shell: openvpn --genkey --secret /etc/openvpn/static.key
    
    - name: set rigts
      file: 
        path: /etc/openvpn/static.key
        owner: openvpn
        group: openvpn
        mode: '0644'

    - name: copy static key to local
      fetch:
        src: /etc/openvpn/static.key
        dest: files/
    
    - name: copy config to server
      copy: 
        src: files/server.conf
        dest: /etc/openvpn/server.conf
        owner: openvpn
        group: openvpn
        mode: '0644'
      notify: 
        - start ovpn
  
  handlers:
    - name: start ovpn
      systemd:
        name: '{{ item }}'
        enabled: yes
        masked: no
        state: restarted
      with_items:
        - 'openvpn@{{ ansible_hostname }}'
            
- hosts: client
  become: yes
  tasks:
    - name: copy from localhost
      copy:
        src: '{{ item }}'
        dest: /etc/openvpn/
        owner: openvpn
        group: openvpn
        mode: '0644'
      with_items:
        - files/server/etc/openvpn/static.key
        - files/client.conf
      notify: 
        - start ovpn
 
  handlers:
    - name: start ovpn
      systemd:
        name: '{{ item }}'
        enabled: yes
        masked: no
        state: restarted
      with_items:
        - 'openvpn@{{ ansible_hostname }}'


        
...
