# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :server1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.0.10.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "PR1"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        


        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "server1"
          box.vm.network "forwarded_port", guest: 80, host: 80
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
	    yes | cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
	    iptables -F
            iptables -X
	    yum install -y epel-release
	    yum install -y nginx
	    mkdir -p /usr/share/nginx/web
	    cp -f /vagrant/conf/index.html /usr/share/nginx/web
	    cp -f /vagrant/conf/web.conf /etc/nginx/conf.d/
	    systemctl enable nginx
	    systemctl start nginx
            SHELL
         end
        end
       end
      end
