# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :R1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.1.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "PR1"},
                   {ip: '10.3.0.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "PR3"},
                   {ip: '192.168.1.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "PR4"},
                ]
  },
    :R2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.1.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "PR1"},
                   {ip: '10.2.0.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "PR2"},
                   {ip: '192.168.2.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "PR5"},
                ]
                
  },
  :R3 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.2.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "PR2"},
                   {ip: '10.3.0.2',  adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "PR3"},
                   {ip: '192.168.3.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "PR6"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "R1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
	    iptables -F
            iptables -X
            SHELL
	when "R2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
	    iptables -F
            iptables -X
            SHELL
        when "R3"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
	    iptables -F
            iptables -X
            SHELL
         end
        end
       end
      end
