Vagrant.configure(2) do |config|
	
    config.vm.define "log" do |log|
	log.vm.box = "centos/7"
	log.vm.hostname = "log"
	log.vm.network "private_network", ip: "192.168.11.151"
	log.vm.define "log"
	log.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end
    	log.vm.provision "shell", inline: <<-SHELL
    	    yes | cp -rf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            systemctl stop firewalld
            setenforce 0
            yum install -y nano rsyslog
            yes | cp -f /vagrant/conf/log/rsyslog.conf /etc/
            systemctl restart rsyslog.service
          SHELL
	end
    config.vm.define "web" do |web|
	web.vm.box = "centos/7"
	web.vm.hostname = "web"
	web.vm.network "private_network", ip: "192.168.11.150"
	web.vm.define "web"
	web.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end
        web.vm.provision "shell", inline: <<-SHELL
    	    yes | cp -rf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            systemctl stop firewalld
            setenforce 0
	    yum install -y epel-release nano rsyslog
	    yum install -y nginx
	    yes | cp -f /vagrant/conf/web/nginx.conf /etc/nginx
            yes | cp -f /vagrant/conf/web/rsyslog.conf /etc/
            cp -f /vagrant/conf/web/audit.conf /etc/rsyslog.d/
            cp -f /vagrant/conf/web/nginx_error.conf /etc/rsyslog.d/
            systemctl enable nginx.service && systemctl start nginx.service && systemctl restart rsyslog.service          
          SHELL
        end
    end
