Vagrant.configure(2) do |config|
	
    config.vm.define "test1Client" do |test1Client|
	test1Client.vm.box = "centos/7"
	test1Client.vm.hostname = "test1Client"
	test1Client.vm.network "private_network", ip: "0.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "test1"
	test1Client.vm.define "test1Client"
	test1Client.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
            vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
          end
    	test1Client.vm.provision "shell", inline: <<-SHELL
    	    yes | cp -rf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            setenforce 0
            yum remove -y NetworkManager
            yum install -y nano tcpdump net-tools 
          SHELL
	end
	

    config.vm.define "virtualswitch" do |virtualswitch|
	virtualswitch.vm.box = "centos/7"
	virtualswitch.vm.hostname = "virtualswitch"
	virtualswitch.vm.network "private_network", ip: "0.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "test1"
	virtualswitch.vm.network "private_network", ip: "0.0.0.0",  adapter: 4, auto_config: false, virtualbox__intnet: "test-central"
	virtualswitch.vm.define "virtualswitch"
	virtualswitch.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
            vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
          end
    	virtualswitch.vm.provision "shell", inline: <<-SHELL
    	    yes | cp -rf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            setenforce 0
            yum remove -y NetworkManager
            yum install -y nano tcpdump 
          SHELL
	end
	
    config.vm.define "centralRouter" do |centralRouter|
	centralRouter.vm.box = "centos/7"
	centralRouter.vm.hostname = "centralRouter"
	centralRouter.vm.network "private_network", ip: "0.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "test-central"
	centralRouter.vm.network "private_network", ip: "0.0.0.0", adapter: 3, auto_config: false, virtualbox__intnet: "central"
	centralRouter.vm.define "centralRouter"
	centralRouter.vm.provider :virtualbox do |vb|
#            vb.customize ["modifyvm", :id, "--memory", "256"]
            vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
          end
    	centralRouter.vm.provision "shell", inline: <<-SHELL
    	    yes | cp -rf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            setenforce 0
            yum remove -y NetworkManager
            yum install -y nano tcpdump 
          SHELL
	end

    end
