---
# tasks file for deploy_nginx

- name: Install EPEL CentOs
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
  tags: 
    - epel-package
    - packages
       
- name: NGINX | Install NGINX CentOs
  yum: 
    name: nginx
    state: latest
  notify: 
    - restart nginx
  tags:
    - nginx-package
    - packages
  when: ansible_os_family == "RedHat"

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags: 
    - nginx-configuration
...