- name: NGINX | Install NGINX Debian
  apt: 
    name: nginx
    state: latest
    update_cache: yes
  notify: 
    - restart nginx
  tags:
    - nginx-package
    - packages
  when: ansible_os_family == "Debian"

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags: 
    - nginx-configuration