# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.1.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "PR1"},
                ]
  },
    :client => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.1.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "PR1"},
                ]
                
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
	    yes | cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
	    iptables -F
            iptables -X
            SHELL
	when "client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
            yes | cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
	    iptables -F
            iptables -X
            SHELL
         end
        end
       end
      end
